### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by aloasut** [whiteCcinn/httprunner-docker#1]
Centos 7 x64/docker-ce latest stable
运行demo的时候：
[root@docker httprunner-docker]# docker run -it --rm -v "$PWD":/usr/src/myapp httprunner ./testcases/demo.json
INFO     Loading environment variables from /usr/src/myapp/.env
ModuleNotFoundError: No module named 'jsonschema'

**Comment by whiteCcinn** [comment]
@aloasut 你改过dockerfile吧？
